gx.evt.autoSkip = false;
gx.define('wwpbaseobjects.home', false, function () {
   this.ServerClass =  "wwpbaseobjects.home" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
   };
   this.s112_client=function()
   {
      gx.fn.setCtrlProperty("MAINNUMBERSSECTION","Visible", ((1==2)) );
      gx.fn.setCtrlProperty("VIDEOSECTION","Visible", ((1==2)) );
   };
   this.e15072_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e16072_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,150,153,154,155,156,157,158,159,160,161,162,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179];
   this.GXLastCtrlId =179;
   this.StudiosgridContainer = new gx.grid.grid(this, 2,"WbpLvl2",124,"Studiosgrid","Studiosgrid","StudiosgridContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.home",[],true,1,false,true,0,false,false,false,"CollWWPBaseObjects\SDTLandingPurusStudios.SDTLandingPurusStudiosItem",0,"px",0,"px","Nueva fila",false,false,false,gx.grid.flexGrid,null,false,"AV12SDTLandingPurusStudioSample",true,[1,1,1,1],false,0,false,false);
   var StudiosgridContainer = this.StudiosgridContainer;
   StudiosgridContainer.startDiv(125,"Unnamedtablefsstudiosgrid","0px","0px");
   StudiosgridContainer.startDiv(126,"","0px","0px");
   StudiosgridContainer.startDiv(127,"","0px","0px");
   StudiosgridContainer.startDiv(128,"Unnamedtable2","0px","0px");
   StudiosgridContainer.startDiv(129,"","0px","0px");
   StudiosgridContainer.startDiv(130,"","0px","0px");
   StudiosgridContainer.addLabel();
   StudiosgridContainer.addBitmap("Sdtlandingpurusstudiosample__studioimage","SDTLANDINGPURUSSTUDIOSAMPLE__STUDIOIMAGE",131,0,"",0,"",null,"","","AttributeLandingPurusStudioImage","");
   StudiosgridContainer.endDiv();
   StudiosgridContainer.endDiv();
   StudiosgridContainer.startDiv(132,"","0px","0px");
   StudiosgridContainer.startDiv(133,"","0px","0px");
   StudiosgridContainer.addLabel();
   StudiosgridContainer.addSingleLineEdit("GXV3",134,"SDTLANDINGPURUSSTUDIOSAMPLE__STUDIOTITLE","","","StudioTitle","svchar",40,"chr",40,40,"left",null,[],"GXV3","GXV3",true,0,false,false,"AttributeLandingPurusSimpleTitle",1,"");
   StudiosgridContainer.endDiv();
   StudiosgridContainer.endDiv();
   StudiosgridContainer.startDiv(135,"","0px","0px");
   StudiosgridContainer.startDiv(136,"","0px","0px");
   StudiosgridContainer.addLabel();
   StudiosgridContainer.addMultipleLineEdit("GXV4",137,"SDTLANDINGPURUSSTUDIOSAMPLE__STUDIODESCRIPTION","","StudioDescription","svchar",80,"chr",5,"row","400",400,"left",null,true,false,0,"");
   StudiosgridContainer.endDiv();
   StudiosgridContainer.endDiv();
   StudiosgridContainer.endDiv();
   StudiosgridContainer.endDiv();
   StudiosgridContainer.endDiv();
   StudiosgridContainer.endDiv();
   this.StudiosgridContainer.emptyText = "";
   StudiosgridContainer.setRenderProp("Class", "Class", "FreeStyleGrid", "str");
   StudiosgridContainer.setRenderProp("Enabled", "Enabled", true, "boolean");
   StudiosgridContainer.setRenderProp("FlexDirection", "Flexdirection", "row", "str");
   StudiosgridContainer.setRenderProp("FlexWrap", "Flexwrap", "wrap", "str");
   StudiosgridContainer.setRenderProp("JustifyContent", "Justifycontent", "space-around", "str");
   StudiosgridContainer.setRenderProp("AlignItems", "Alignitems", "stretch", "str");
   StudiosgridContainer.setRenderProp("AlignContent", "Aligncontent", "space-around", "str");
   StudiosgridContainer.setRenderProp("Visible", "Visible", true, "boolean");
   this.setGrid(StudiosgridContainer);
   this.CustomersgridContainer = new gx.grid.grid(this, 4,"WbpLvl4",149,"Customersgrid","Customersgrid","CustomersgridContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.home",[],true,6,false,true,0,false,false,false,"CollWWPBaseObjects\SDTHomeLandingSampleLogos.SDTHomeLandingSampleLogosItem",0,"px",0,"px","Nueva fila",false,false,false,gx.uc.HorizontalGrid,null,false,"AV18SDTHomeLandingSampleLogos",true,[2,3,3,6],false,0,false,false);
   var CustomersgridContainer = this.CustomersgridContainer;
   CustomersgridContainer.startTable("Unnamedtablefscustomersgrid",150,"0px");
   CustomersgridContainer.startRow("","","","","","");
   CustomersgridContainer.startCell("","","","","","","","","","");
   CustomersgridContainer.startDiv(153,"","0px","0px");
   CustomersgridContainer.addLabel();
   CustomersgridContainer.addBitmap("Sdthomelandingsamplelogos__logo","SDTHOMELANDINGSAMPLELOGOS__LOGO",154,0,"",0,"",null,"","","AttributeLandingPurusCustomersImage","");
   CustomersgridContainer.endDiv();
   CustomersgridContainer.endCell();
   CustomersgridContainer.endRow();
   CustomersgridContainer.endTable();
   this.CustomersgridContainer.emptyText = "";
   CustomersgridContainer.setRenderProp("Class", "Class", "FreeStyleGrid", "str");
   CustomersgridContainer.setRenderProp("Enabled", "Enabled", true, "boolean");
   CustomersgridContainer.setRenderProp("Paged", "Paged", true, "bool");
   CustomersgridContainer.setRenderDynProp("ShowPageController", "Showpagecontroller", true, "bool");
   CustomersgridContainer.setRenderProp("PageControllerClass", "Pagecontrollerclass", "GridPageController", "str");
   CustomersgridContainer.setRenderProp("ShowArrows", "Showarrows", true, "bool");
   CustomersgridContainer.setRenderDynProp("Infinite", "Infinite", false, "bool");
   CustomersgridContainer.setRenderDynProp("AutoPlay", "Autoplay", false, "bool");
   CustomersgridContainer.setRenderProp("AutoPlaySpeed", "Autoplayspeed", 3000, "num");
   CustomersgridContainer.setRenderProp("VariableWidth", "Variablewidth", false, "bool");
   CustomersgridContainer.setRenderProp("MultiRowsExtraSmall", "Multi_rows_xs", 1, "num");
   CustomersgridContainer.setRenderProp("MultiRowsSmall", "Multi_rows_sm", 1, "num");
   CustomersgridContainer.setRenderProp("MultiRowsMedium", "Multi_rows_md", 1, "num");
   CustomersgridContainer.setRenderProp("MultiRowsLarge", "Multi_rows_lg", 1, "num");
   CustomersgridContainer.setRenderProp("CurrentPage", "Currentpage", '', "int");
   CustomersgridContainer.setRenderProp("Visible", "Visible", true, "boolean");
   this.setGrid(CustomersgridContainer);
   this.FstestimonialsContainer = new gx.grid.grid(this, 3,"WbpLvl3",163,"Fstestimonials","Fstestimonials","FstestimonialsContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.home",[],true,3,false,true,0,false,false,false,"CollWWPBaseObjects\SDTHomeTestimonials.SDTHomeTestimonialsItem",0,"px",0,"px","Nueva fila",false,false,false,gx.uc.HorizontalGrid,null,false,"AV16SDTHomeTestimonials",true,[1,3,3,3],false,0,false,false);
   var FstestimonialsContainer = this.FstestimonialsContainer;
   FstestimonialsContainer.startDiv(164,"Unnamedtablefsfstestimonials","0px","0px");
   FstestimonialsContainer.startDiv(165,"","0px","0px");
   FstestimonialsContainer.startDiv(166,"","0px","0px");
   FstestimonialsContainer.startDiv(167,"","0px","0px");
   FstestimonialsContainer.addLabel();
   FstestimonialsContainer.addMultipleLineEdit("GXV8",168,"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSDESCRIPTION","","SDTHomeTestimonialsDescription","svchar",80,"chr",5,"row","400",400,"left",null,true,false,0,"");
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.startDiv(169,"","0px","0px");
   FstestimonialsContainer.startDiv(170,"","0px","0px");
   FstestimonialsContainer.startDiv(171,"Unnamedtable1","0px","0px");
   FstestimonialsContainer.startDiv(172,"","0px","0px");
   FstestimonialsContainer.startDiv(173,"","0px","0px");
   FstestimonialsContainer.startDiv(174,"","0px","0px");
   FstestimonialsContainer.addLabel();
   FstestimonialsContainer.addSingleLineEdit("GXV9",175,"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSNAME","","","SDTHomeTestimonialsName","svchar",40,"chr",40,40,"left",null,[],"GXV9","GXV9",true,0,false,false,"AttributeLandingPurusTestimonialTitle",1,"");
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.startDiv(176,"","0px","0px");
   FstestimonialsContainer.startDiv(177,"","0px","0px");
   FstestimonialsContainer.startDiv(178,"","0px","0px");
   FstestimonialsContainer.addLabel();
   FstestimonialsContainer.addSingleLineEdit("GXV10",179,"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSCOMPANY","","","SDTHomeTestimonialsCompany","svchar",40,"chr",40,40,"left",null,[],"GXV10","GXV10",true,0,false,false,"AttributeLandingPurusTestimonialSubtitle",1,"");
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   this.FstestimonialsContainer.emptyText = "";
   FstestimonialsContainer.setRenderProp("Class", "Class", "FreeStyleGrid", "str");
   FstestimonialsContainer.setRenderProp("Enabled", "Enabled", true, "boolean");
   FstestimonialsContainer.setRenderProp("Paged", "Paged", true, "bool");
   FstestimonialsContainer.setRenderProp("ShowPageController", "Showpagecontroller", true, "bool");
   FstestimonialsContainer.setRenderProp("PageControllerClass", "Pagecontrollerclass", "GridPageController", "str");
   FstestimonialsContainer.setRenderProp("ShowArrows", "Showarrows", true, "bool");
   FstestimonialsContainer.setRenderProp("Infinite", "Infinite", false, "bool");
   FstestimonialsContainer.setRenderProp("AutoPlay", "Autoplay", false, "bool");
   FstestimonialsContainer.setRenderProp("AutoPlaySpeed", "Autoplayspeed", 3000, "num");
   FstestimonialsContainer.setRenderProp("VariableWidth", "Variablewidth", false, "bool");
   FstestimonialsContainer.setRenderProp("MultiRowsExtraSmall", "Multi_rows_xs", 1, "num");
   FstestimonialsContainer.setRenderProp("MultiRowsSmall", "Multi_rows_sm", 1, "num");
   FstestimonialsContainer.setRenderProp("MultiRowsMedium", "Multi_rows_md", 1, "num");
   FstestimonialsContainer.setRenderProp("MultiRowsLarge", "Multi_rows_lg", 1, "num");
   FstestimonialsContainer.setRenderProp("CurrentPage", "Currentpage", '', "int");
   FstestimonialsContainer.setRenderProp("Visible", "Visible", true, "boolean");
   this.setGrid(FstestimonialsContainer);
   this.COMPANYVIDEOContainer = gx.uc.getNew(this, 58, 0, "GXMediaPlayer", "COMPANYVIDEOContainer", "Companyvideo", "COMPANYVIDEO");
   var COMPANYVIDEOContainer = this.COMPANYVIDEOContainer;
   COMPANYVIDEOContainer.setProp("Class", "Class", "", "char");
   COMPANYVIDEOContainer.setProp("Enabled", "Enabled", true, "boolean");
   COMPANYVIDEOContainer.setProp("Width", "Width", "100%", "str");
   COMPANYVIDEOContainer.setProp("Height", "Height", "527", "str");
   COMPANYVIDEOContainer.setProp("Source", "Source", "https://youtu.be/pGcoKBBrK14", "str");
   COMPANYVIDEOContainer.setProp("Autoplay", "Autoplay", "false", "str");
   COMPANYVIDEOContainer.setProp("FullScreen", "Fullscreen", "false", "str");
   COMPANYVIDEOContainer.setProp("MediaTitle", "Mediatitle", "", "str");
   COMPANYVIDEOContainer.setProp("Visible", "Visible", true, "bool");
   COMPANYVIDEOContainer.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   COMPANYVIDEOContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(COMPANYVIDEOContainer);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"SLOGANSECTION",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"",grid:0};
   GXValidFnc[12]={ id: 12, fld:"SLOGANTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[13]={ id: 13, fld:"",grid:0};
   GXValidFnc[14]={ id: 14, fld:"",grid:0};
   GXValidFnc[15]={ id: 15, fld:"SLOGANSUBTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[16]={ id: 16, fld:"",grid:0};
   GXValidFnc[17]={ id: 17, fld:"",grid:0};
   GXValidFnc[18]={ id: 18, fld:"MAINNUMBERSSECTION",grid:0};
   GXValidFnc[19]={ id: 19, fld:"",grid:0};
   GXValidFnc[20]={ id: 20, fld:"",grid:0};
   GXValidFnc[21]={ id: 21, fld:"MAINNUMBERSTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[22]={ id: 22, fld:"",grid:0};
   GXValidFnc[23]={ id: 23, fld:"",grid:0};
   GXValidFnc[24]={ id: 24, fld:"MAINNUMBERSSUBTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[25]={ id: 25, fld:"",grid:0};
   GXValidFnc[26]={ id: 26, fld:"",grid:0};
   GXValidFnc[27]={ id: 27, fld:"UNNAMEDTABLE5",grid:0};
   GXValidFnc[28]={ id: 28, fld:"",grid:0};
   GXValidFnc[29]={ id: 29, fld:"",grid:0};
   GXValidFnc[30]={ id: 30, fld:"UNNAMEDTABLE6",grid:0};
   GXValidFnc[31]={ id: 31, fld:"",grid:0};
   GXValidFnc[32]={ id: 32, fld:"",grid:0};
   GXValidFnc[33]={ id: 33, fld:"MAINNUMBERS_ICON1",grid:0};
   GXValidFnc[34]={ id: 34, fld:"",grid:0};
   GXValidFnc[35]={ id: 35, fld:"",grid:0};
   GXValidFnc[36]={ id: 36, fld:"QW", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[37]={ id: 37, fld:"",grid:0};
   GXValidFnc[38]={ id: 38, fld:"UNNAMEDTABLE7",grid:0};
   GXValidFnc[39]={ id: 39, fld:"",grid:0};
   GXValidFnc[40]={ id: 40, fld:"",grid:0};
   GXValidFnc[41]={ id: 41, fld:"MAINNUMBERS_ICON2",grid:0};
   GXValidFnc[42]={ id: 42, fld:"",grid:0};
   GXValidFnc[43]={ id: 43, fld:"",grid:0};
   GXValidFnc[44]={ id: 44, fld:"QWASD", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[45]={ id: 45, fld:"",grid:0};
   GXValidFnc[46]={ id: 46, fld:"UNNAMEDTABLE8",grid:0};
   GXValidFnc[47]={ id: 47, fld:"",grid:0};
   GXValidFnc[48]={ id: 48, fld:"",grid:0};
   GXValidFnc[49]={ id: 49, fld:"MAINNUMBERS_ICON3",grid:0};
   GXValidFnc[50]={ id: 50, fld:"",grid:0};
   GXValidFnc[51]={ id: 51, fld:"",grid:0};
   GXValidFnc[52]={ id: 52, fld:"QWFD", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[53]={ id: 53, fld:"",grid:0};
   GXValidFnc[54]={ id: 54, fld:"",grid:0};
   GXValidFnc[55]={ id: 55, fld:"VIDEOSECTION",grid:0};
   GXValidFnc[56]={ id: 56, fld:"",grid:0};
   GXValidFnc[57]={ id: 57, fld:"",grid:0};
   GXValidFnc[59]={ id: 59, fld:"",grid:0};
   GXValidFnc[60]={ id: 60, fld:"",grid:0};
   GXValidFnc[61]={ id: 61, fld:"FEATURESSECTION2",grid:0};
   GXValidFnc[62]={ id: 62, fld:"",grid:0};
   GXValidFnc[63]={ id: 63, fld:"",grid:0};
   GXValidFnc[64]={ id: 64, fld:"FEATURESTITLE2", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[65]={ id: 65, fld:"",grid:0};
   GXValidFnc[66]={ id: 66, fld:"",grid:0};
   GXValidFnc[67]={ id: 67, fld:"FEATURESSUBTITLE12", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[68]={ id: 68, fld:"",grid:0};
   GXValidFnc[69]={ id: 69, fld:"",grid:0};
   GXValidFnc[70]={ id: 70, fld:"FEATURESSUBTITLE22", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[71]={ id: 71, fld:"",grid:0};
   GXValidFnc[72]={ id: 72, fld:"",grid:0};
   GXValidFnc[73]={ id: 73, fld:"FEATURESSUBTITLE222", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[74]={ id: 74, fld:"",grid:0};
   GXValidFnc[75]={ id: 75, fld:"",grid:0};
   GXValidFnc[76]={ id: 76, fld:"FEATURESSUBTITLE2222", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[77]={ id: 77, fld:"",grid:0};
   GXValidFnc[78]={ id: 78, fld:"",grid:0};
   GXValidFnc[79]={ id: 79, fld:"UNNAMEDTABLE4",grid:0};
   GXValidFnc[80]={ id: 80, fld:"",grid:0};
   GXValidFnc[81]={ id: 81, fld:"LANDINDPURUSFEATURESLEFT2",grid:0};
   GXValidFnc[82]={ id: 82, fld:"",grid:0};
   GXValidFnc[83]={ id: 83, fld:"LANDINGPURUSFEATURESCENTER2",grid:0};
   GXValidFnc[84]={ id: 84, fld:"",grid:0};
   GXValidFnc[85]={ id: 85, fld:"LANDINGPURUSFEATURESRIGHT2",grid:0};
   GXValidFnc[86]={ id: 86, fld:"",grid:0};
   GXValidFnc[87]={ id: 87, fld:"",grid:0};
   GXValidFnc[88]={ id: 88, fld:"FEATURESSECTION",grid:0};
   GXValidFnc[89]={ id: 89, fld:"",grid:0};
   GXValidFnc[90]={ id: 90, fld:"",grid:0};
   GXValidFnc[91]={ id: 91, fld:"FEATURESTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[92]={ id: 92, fld:"",grid:0};
   GXValidFnc[93]={ id: 93, fld:"",grid:0};
   GXValidFnc[94]={ id: 94, fld:"FEATURESSUBTITLE1", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[95]={ id: 95, fld:"",grid:0};
   GXValidFnc[96]={ id: 96, fld:"",grid:0};
   GXValidFnc[97]={ id: 97, fld:"FEATURESSUBTITLE2", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[98]={ id: 98, fld:"",grid:0};
   GXValidFnc[99]={ id: 99, fld:"",grid:0};
   GXValidFnc[100]={ id: 100, fld:"FEATURESSUBTITLE2A", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[101]={ id: 101, fld:"",grid:0};
   GXValidFnc[102]={ id: 102, fld:"",grid:0};
   GXValidFnc[103]={ id: 103, fld:"FEATURESSUBTITLE2AW", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[104]={ id: 104, fld:"",grid:0};
   GXValidFnc[105]={ id: 105, fld:"",grid:0};
   GXValidFnc[106]={ id: 106, fld:"UNNAMEDTABLE3",grid:0};
   GXValidFnc[107]={ id: 107, fld:"",grid:0};
   GXValidFnc[108]={ id: 108, fld:"LANDINDPURUSFEATURESLEFT",grid:0};
   GXValidFnc[109]={ id: 109, fld:"",grid:0};
   GXValidFnc[110]={ id: 110, fld:"LANDINGPURUSFEATURESCENTER",grid:0};
   GXValidFnc[111]={ id: 111, fld:"",grid:0};
   GXValidFnc[112]={ id: 112, fld:"LANDINGPURUSFEATURESRIGHT",grid:0};
   GXValidFnc[113]={ id: 113, fld:"",grid:0};
   GXValidFnc[114]={ id: 114, fld:"",grid:0};
   GXValidFnc[115]={ id: 115, fld:"STUDIOSSECTION",grid:0};
   GXValidFnc[116]={ id: 116, fld:"",grid:0};
   GXValidFnc[117]={ id: 117, fld:"",grid:0};
   GXValidFnc[118]={ id: 118, fld:"STUDIOSTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[119]={ id: 119, fld:"",grid:0};
   GXValidFnc[120]={ id: 120, fld:"",grid:0};
   GXValidFnc[121]={ id: 121, fld:"STUDIOSSUBTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[122]={ id: 122, fld:"",grid:0};
   GXValidFnc[123]={ id: 123, fld:"",grid:0};
   GXValidFnc[125]={ id: 125, fld:"UNNAMEDTABLEFSSTUDIOSGRID",grid:124};
   GXValidFnc[126]={ id: 126, fld:"",grid:124};
   GXValidFnc[127]={ id: 127, fld:"",grid:124};
   GXValidFnc[128]={ id: 128, fld:"UNNAMEDTABLE2",grid:124};
   GXValidFnc[129]={ id: 129, fld:"",grid:124};
   GXValidFnc[130]={ id: 130, fld:"",grid:124};
   GXValidFnc[131]={ id:131 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:124,gxgrid:this.StudiosgridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTLANDINGPURUSSTUDIOSAMPLE__STUDIOIMAGE",gxz:"ZV23GXV2",gxold:"OV23GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.GXV2=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV23GXV2=Value},v2c:function(row){gx.fn.setGridMultimediaValue("SDTLANDINGPURUSSTUDIOSAMPLE__STUDIOIMAGE",row || gx.fn.currentGridRowImpl(124),gx.O.GXV2,"")},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV2=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTLANDINGPURUSSTUDIOSAMPLE__STUDIOIMAGE",row || gx.fn.currentGridRowImpl(124))},nac:gx.falseFn};
   GXValidFnc[132]={ id: 132, fld:"",grid:124};
   GXValidFnc[133]={ id: 133, fld:"",grid:124};
   GXValidFnc[134]={ id:134 ,lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:124,gxgrid:this.StudiosgridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTLANDINGPURUSSTUDIOSAMPLE__STUDIOTITLE",gxz:"ZV24GXV3",gxold:"OV24GXV3",gxvar:"GXV3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV3=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV24GXV3=Value},v2c:function(row){gx.fn.setGridControlValue("SDTLANDINGPURUSSTUDIOSAMPLE__STUDIOTITLE",row || gx.fn.currentGridRowImpl(124),gx.O.GXV3,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV3=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTLANDINGPURUSSTUDIOSAMPLE__STUDIOTITLE",row || gx.fn.currentGridRowImpl(124))},nac:gx.falseFn};
   GXValidFnc[135]={ id: 135, fld:"",grid:124};
   GXValidFnc[136]={ id: 136, fld:"",grid:124};
   GXValidFnc[137]={ id:137 ,lvl:2,type:"svchar",len:400,dec:0,sign:false,ro:1,isacc:0, multiline:true,grid:124,gxgrid:this.StudiosgridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTLANDINGPURUSSTUDIOSAMPLE__STUDIODESCRIPTION",gxz:"ZV25GXV4",gxold:"OV25GXV4",gxvar:"GXV4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV4=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV25GXV4=Value},v2c:function(row){gx.fn.setGridControlValue("SDTLANDINGPURUSSTUDIOSAMPLE__STUDIODESCRIPTION",row || gx.fn.currentGridRowImpl(124),gx.O.GXV4,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV4=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTLANDINGPURUSSTUDIOSAMPLE__STUDIODESCRIPTION",row || gx.fn.currentGridRowImpl(124))},nac:gx.falseFn};
   GXValidFnc[138]={ id: 138, fld:"",grid:0};
   GXValidFnc[139]={ id: 139, fld:"",grid:0};
   GXValidFnc[140]={ id: 140, fld:"CLIENTSSECTION",grid:0};
   GXValidFnc[141]={ id: 141, fld:"",grid:0};
   GXValidFnc[142]={ id: 142, fld:"",grid:0};
   GXValidFnc[143]={ id: 143, fld:"CLIENTSTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[144]={ id: 144, fld:"",grid:0};
   GXValidFnc[145]={ id: 145, fld:"",grid:0};
   GXValidFnc[146]={ id: 146, fld:"CUSTOMERSSUBTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[147]={ id: 147, fld:"",grid:0};
   GXValidFnc[148]={ id: 148, fld:"",grid:0};
   GXValidFnc[150]={ id: 150, fld:"UNNAMEDTABLEFSCUSTOMERSGRID",grid:149};
   GXValidFnc[153]={ id: 153, fld:"",grid:149};
   GXValidFnc[154]={ id:154 ,lvl:4,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:149,gxgrid:this.CustomersgridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTHOMELANDINGSAMPLELOGOS__LOGO",gxz:"ZV27GXV6",gxold:"OV27GXV6",gxvar:"GXV6",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.GXV6=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV27GXV6=Value},v2c:function(row){gx.fn.setGridMultimediaValue("SDTHOMELANDINGSAMPLELOGOS__LOGO",row || gx.fn.currentGridRowImpl(149),gx.O.GXV6,"")},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV6=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTHOMELANDINGSAMPLELOGOS__LOGO",row || gx.fn.currentGridRowImpl(149))},nac:gx.falseFn};
   GXValidFnc[155]={ id: 155, fld:"",grid:0};
   GXValidFnc[156]={ id: 156, fld:"",grid:0};
   GXValidFnc[157]={ id: 157, fld:"TESTIMONIALSSECTION",grid:0};
   GXValidFnc[158]={ id: 158, fld:"",grid:0};
   GXValidFnc[159]={ id: 159, fld:"",grid:0};
   GXValidFnc[160]={ id: 160, fld:"TESTIMONIALSTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[161]={ id: 161, fld:"",grid:0};
   GXValidFnc[162]={ id: 162, fld:"",grid:0};
   GXValidFnc[164]={ id: 164, fld:"UNNAMEDTABLEFSFSTESTIMONIALS",grid:163};
   GXValidFnc[165]={ id: 165, fld:"",grid:163};
   GXValidFnc[166]={ id: 166, fld:"",grid:163};
   GXValidFnc[167]={ id: 167, fld:"",grid:163};
   GXValidFnc[168]={ id:168 ,lvl:3,type:"svchar",len:400,dec:0,sign:false,ro:1,isacc:0, multiline:true,grid:163,gxgrid:this.FstestimonialsContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSDESCRIPTION",gxz:"ZV29GXV8",gxold:"OV29GXV8",gxvar:"GXV8",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV8=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV29GXV8=Value},v2c:function(row){gx.fn.setGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSDESCRIPTION",row || gx.fn.currentGridRowImpl(163),gx.O.GXV8,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV8=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSDESCRIPTION",row || gx.fn.currentGridRowImpl(163))},nac:gx.falseFn};
   GXValidFnc[169]={ id: 169, fld:"",grid:163};
   GXValidFnc[170]={ id: 170, fld:"",grid:163};
   GXValidFnc[171]={ id: 171, fld:"UNNAMEDTABLE1",grid:163};
   GXValidFnc[172]={ id: 172, fld:"",grid:163};
   GXValidFnc[173]={ id: 173, fld:"",grid:163};
   GXValidFnc[174]={ id: 174, fld:"",grid:163};
   GXValidFnc[175]={ id:175 ,lvl:3,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:163,gxgrid:this.FstestimonialsContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSNAME",gxz:"ZV30GXV9",gxold:"OV30GXV9",gxvar:"GXV9",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV9=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV30GXV9=Value},v2c:function(row){gx.fn.setGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSNAME",row || gx.fn.currentGridRowImpl(163),gx.O.GXV9,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV9=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSNAME",row || gx.fn.currentGridRowImpl(163))},nac:gx.falseFn};
   GXValidFnc[176]={ id: 176, fld:"",grid:163};
   GXValidFnc[177]={ id: 177, fld:"",grid:163};
   GXValidFnc[178]={ id: 178, fld:"",grid:163};
   GXValidFnc[179]={ id:179 ,lvl:3,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:163,gxgrid:this.FstestimonialsContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSCOMPANY",gxz:"ZV31GXV10",gxold:"OV31GXV10",gxvar:"GXV10",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV10=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV31GXV10=Value},v2c:function(row){gx.fn.setGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSCOMPANY",row || gx.fn.currentGridRowImpl(163),gx.O.GXV10,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV10=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSCOMPANY",row || gx.fn.currentGridRowImpl(163))},nac:gx.falseFn};
   this.ZV23GXV2 = "" ;
   this.OV23GXV2 = "" ;
   this.ZV24GXV3 = "" ;
   this.OV24GXV3 = "" ;
   this.ZV25GXV4 = "" ;
   this.OV25GXV4 = "" ;
   this.ZV27GXV6 = "" ;
   this.OV27GXV6 = "" ;
   this.ZV29GXV8 = "" ;
   this.OV29GXV8 = "" ;
   this.ZV30GXV9 = "" ;
   this.OV30GXV9 = "" ;
   this.ZV31GXV10 = "" ;
   this.OV31GXV10 = "" ;
   this.GXV2 = "" ;
   this.GXV3 = "" ;
   this.GXV4 = "" ;
   this.GXV6 = "" ;
   this.GXV8 = "" ;
   this.GXV9 = "" ;
   this.GXV10 = "" ;
   this.Events = {"e15072_client": ["ENTER", true] ,"e16072_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'STUDIOSGRID_nFirstRecordOnPage'},{av:'STUDIOSGRID_nEOF'},{av:'AV12SDTLandingPurusStudioSample',fld:'vSDTLANDINGPURUSSTUDIOSAMPLE',grid:124,pic:''},{av:'nRC_GXsfl_124',ctrl:'STUDIOSGRID',prop:'GridRC'},{av:'FSTESTIMONIALS_nFirstRecordOnPage'},{av:'FSTESTIMONIALS_nEOF'},{av:'AV16SDTHomeTestimonials',fld:'vSDTHOMETESTIMONIALS',grid:163,pic:''},{av:'nRC_GXsfl_163',ctrl:'FSTESTIMONIALS',prop:'GridRC'},{av:'CUSTOMERSGRID_nFirstRecordOnPage'},{av:'CUSTOMERSGRID_nEOF'},{av:'AV18SDTHomeLandingSampleLogos',fld:'vSDTHOMELANDINGSAMPLELOGOS',grid:149,pic:''},{av:'nRC_GXsfl_149',ctrl:'CUSTOMERSGRID',prop:'GridRC'}],[]];
   this.EvtParms["START"] = [[{av:'AV18SDTHomeLandingSampleLogos',fld:'vSDTHOMELANDINGSAMPLELOGOS',grid:149,pic:''},{av:'CUSTOMERSGRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_149',ctrl:'CUSTOMERSGRID',prop:'GridRC'},{av:'STUDIOSGRID_nFirstRecordOnPage'},{av:'STUDIOSGRID_nEOF'},{av:'AV12SDTLandingPurusStudioSample',fld:'vSDTLANDINGPURUSSTUDIOSAMPLE',grid:124,pic:''},{av:'nRC_GXsfl_124',ctrl:'STUDIOSGRID',prop:'GridRC'},{av:'FSTESTIMONIALS_nFirstRecordOnPage'},{av:'FSTESTIMONIALS_nEOF'},{av:'AV16SDTHomeTestimonials',fld:'vSDTHOMETESTIMONIALS',grid:163,pic:''},{av:'nRC_GXsfl_163',ctrl:'FSTESTIMONIALS',prop:'GridRC'},{av:'CUSTOMERSGRID_nEOF'}],[{av:'AV12SDTLandingPurusStudioSample',fld:'vSDTLANDINGPURUSSTUDIOSAMPLE',grid:124,pic:''},{av:'STUDIOSGRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_124',ctrl:'STUDIOSGRID',prop:'GridRC'},{av:'AV16SDTHomeTestimonials',fld:'vSDTHOMETESTIMONIALS',grid:163,pic:''},{av:'FSTESTIMONIALS_nFirstRecordOnPage'},{av:'nRC_GXsfl_163',ctrl:'FSTESTIMONIALS',prop:'GridRC'},{av:'AV18SDTHomeLandingSampleLogos',fld:'vSDTHOMELANDINGSAMPLELOGOS',grid:149,pic:''},{av:'CUSTOMERSGRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_149',ctrl:'CUSTOMERSGRID',prop:'GridRC'},{ctrl:'CUSTOMERSGRID',prop:'Autoplay'},{ctrl:'CUSTOMERSGRID',prop:'Showpagecontroller'},{ctrl:'CUSTOMERSGRID',prop:'Infinite'},{av:'gx.fn.getCtrlProperty("MAINNUMBERSSECTION","Visible")',ctrl:'MAINNUMBERSSECTION',prop:'Visible'},{av:'gx.fn.getCtrlProperty("VIDEOSECTION","Visible")',ctrl:'VIDEOSECTION',prop:'Visible'}]];
   this.EvtParms["FSTESTIMONIALS.LOAD"] = [[],[]];
   this.EvtParms["CUSTOMERSGRID.LOAD"] = [[],[]];
   this.EvtParms["STUDIOSGRID.LOAD"] = [[],[]];
   this.addGridBCProperty("Sdtlandingpurusstudiosample", ["StudioImage"], this.GXValidFnc[131], "AV12SDTLandingPurusStudioSample");
   this.addGridBCProperty("Sdtlandingpurusstudiosample", ["StudioTitle"], this.GXValidFnc[134], "AV12SDTLandingPurusStudioSample");
   this.addGridBCProperty("Sdtlandingpurusstudiosample", ["StudioDescription"], this.GXValidFnc[137], "AV12SDTLandingPurusStudioSample");
   this.addBCProperty("Sdthomelandingsamplelogos", ["Logo"], this.GXValidFnc[149], "AV18SDTHomeLandingSampleLogos");
   this.addGridBCProperty("Sdthometestimonials", ["SDTHomeTestimonialsDescription"], this.GXValidFnc[168], "AV16SDTHomeTestimonials");
   this.addGridBCProperty("Sdthometestimonials", ["SDTHomeTestimonialsName"], this.GXValidFnc[175], "AV16SDTHomeTestimonials");
   this.addGridBCProperty("Sdthometestimonials", ["SDTHomeTestimonialsCompany"], this.GXValidFnc[179], "AV16SDTHomeTestimonials");
   this.Initialize( );
});
gx.wi( function() { gx.createParentObj(wwpbaseobjects.home);});
