gx.evt.autoSkip = false;
gx.define('wwpbaseobjects.noticias', false, function () {
   this.ServerClass =  "wwpbaseobjects.noticias" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
   };
   this.e140s2_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e150s2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51];
   this.GXLastCtrlId =51;
   this.CustomersgridContainer = new gx.grid.grid(this, 2,"WbpLvl2",21,"Customersgrid","Customersgrid","CustomersgridContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.noticias",[],true,1,false,true,0,false,false,false,"CollWWPBaseObjects\SDTHomeLandingSampleLogos.SDTHomeLandingSampleLogosItem",0,"px",0,"px","Nueva fila",false,false,false,gx.grid.flexGrid,null,false,"AV5SDTHomeLandingSampleLogos",true,[3,3,5,6],false,0,false,false);
   var CustomersgridContainer = this.CustomersgridContainer;
   CustomersgridContainer.startDiv(22,"Unnamedtablefscustomersgrid","0px","0px");
   CustomersgridContainer.startDiv(23,"","0px","0px");
   CustomersgridContainer.startDiv(24,"","0px","0px");
   CustomersgridContainer.startDiv(25,"","0px","0px");
   CustomersgridContainer.addLabel();
   CustomersgridContainer.addBitmap("Sdthomelandingsamplelogos__logo","SDTHOMELANDINGSAMPLELOGOS__LOGO",26,0,"",0,"",null,"","","AttributeLandingPurusCustomersImage","");
   CustomersgridContainer.endDiv();
   CustomersgridContainer.endDiv();
   CustomersgridContainer.endDiv();
   CustomersgridContainer.endDiv();
   this.CustomersgridContainer.emptyText = "";
   CustomersgridContainer.setRenderProp("Class", "Class", "FreeStyleGrid", "str");
   CustomersgridContainer.setRenderProp("Enabled", "Enabled", true, "boolean");
   CustomersgridContainer.setRenderProp("FlexDirection", "Flexdirection", "row", "str");
   CustomersgridContainer.setRenderProp("FlexWrap", "Flexwrap", "wrap", "str");
   CustomersgridContainer.setRenderProp("JustifyContent", "Justifycontent", "space-around", "str");
   CustomersgridContainer.setRenderProp("AlignItems", "Alignitems", "stretch", "str");
   CustomersgridContainer.setRenderProp("AlignContent", "Aligncontent", "stretch", "str");
   CustomersgridContainer.setRenderProp("Visible", "Visible", true, "boolean");
   this.setGrid(CustomersgridContainer);
   this.FstestimonialsContainer = new gx.grid.grid(this, 3,"WbpLvl3",35,"Fstestimonials","Fstestimonials","FstestimonialsContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.noticias",[],true,3,false,true,0,false,false,false,"CollWWPBaseObjects\SDTHomeTestimonials.SDTHomeTestimonialsItem",0,"px",0,"px","Nueva fila",false,false,false,gx.uc.HorizontalGrid,null,false,"AV6SDTHomeTestimonials",true,[1,2,3,3],false,0,false,false);
   var FstestimonialsContainer = this.FstestimonialsContainer;
   FstestimonialsContainer.startDiv(36,"Unnamedtablefsfstestimonials","0px","0px");
   FstestimonialsContainer.startDiv(37,"","0px","0px");
   FstestimonialsContainer.startDiv(38,"","0px","0px");
   FstestimonialsContainer.startDiv(39,"","0px","0px");
   FstestimonialsContainer.addLabel();
   FstestimonialsContainer.addMultipleLineEdit("GXV4",40,"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSDESCRIPTION","","SDTHomeTestimonialsDescription","svchar",80,"chr",5,"row","400",400,"left",null,true,false,0,"");
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.startDiv(41,"","0px","0px");
   FstestimonialsContainer.startDiv(42,"","0px","0px");
   FstestimonialsContainer.startDiv(43,"Unnamedtable1","0px","0px");
   FstestimonialsContainer.startDiv(44,"","0px","0px");
   FstestimonialsContainer.startDiv(45,"","0px","0px");
   FstestimonialsContainer.startDiv(46,"","0px","0px");
   FstestimonialsContainer.addLabel();
   FstestimonialsContainer.addSingleLineEdit("GXV5",47,"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSNAME","","","SDTHomeTestimonialsName","svchar",40,"chr",40,40,"left",null,[],"GXV5","GXV5",true,0,false,false,"AttributeLandingPurusTestimonialTitle",1,"");
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.startDiv(48,"","0px","0px");
   FstestimonialsContainer.startDiv(49,"","0px","0px");
   FstestimonialsContainer.startDiv(50,"","0px","0px");
   FstestimonialsContainer.addLabel();
   FstestimonialsContainer.addSingleLineEdit("GXV6",51,"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSCOMPANY","","","SDTHomeTestimonialsCompany","svchar",40,"chr",40,40,"left",null,[],"GXV6","GXV6",true,0,false,false,"AttributeLandingPurusTestimonialSubtitle",1,"");
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   FstestimonialsContainer.endDiv();
   this.FstestimonialsContainer.emptyText = "";
   FstestimonialsContainer.setRenderProp("Class", "Class", "FreeStyleGrid", "str");
   FstestimonialsContainer.setRenderProp("Enabled", "Enabled", true, "boolean");
   FstestimonialsContainer.setRenderProp("Paged", "Paged", true, "bool");
   FstestimonialsContainer.setRenderProp("ShowPageController", "Showpagecontroller", true, "bool");
   FstestimonialsContainer.setRenderProp("PageControllerClass", "Pagecontrollerclass", "GridPageController", "str");
   FstestimonialsContainer.setRenderProp("ShowArrows", "Showarrows", true, "bool");
   FstestimonialsContainer.setRenderProp("Infinite", "Infinite", false, "bool");
   FstestimonialsContainer.setRenderProp("AutoPlay", "Autoplay", false, "bool");
   FstestimonialsContainer.setRenderProp("AutoPlaySpeed", "Autoplayspeed", 3000, "num");
   FstestimonialsContainer.setRenderProp("VariableWidth", "Variablewidth", false, "bool");
   FstestimonialsContainer.setRenderProp("MultiRowsExtraSmall", "Multi_rows_xs", 1, "num");
   FstestimonialsContainer.setRenderProp("MultiRowsSmall", "Multi_rows_sm", 1, "num");
   FstestimonialsContainer.setRenderProp("MultiRowsMedium", "Multi_rows_md", 1, "num");
   FstestimonialsContainer.setRenderProp("MultiRowsLarge", "Multi_rows_lg", 1, "num");
   FstestimonialsContainer.setRenderProp("CurrentPage", "Currentpage", '', "int");
   FstestimonialsContainer.setRenderProp("Visible", "Visible", true, "boolean");
   this.setGrid(FstestimonialsContainer);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"HEADERSECTION",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"",grid:0};
   GXValidFnc[12]={ id: 12, fld:"CUSTOMERSTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[13]={ id: 13, fld:"",grid:0};
   GXValidFnc[14]={ id: 14, fld:"",grid:0};
   GXValidFnc[15]={ id: 15, fld:"CLIENTSSECTION",grid:0};
   GXValidFnc[16]={ id: 16, fld:"",grid:0};
   GXValidFnc[17]={ id: 17, fld:"",grid:0};
   GXValidFnc[18]={ id: 18, fld:"CUSTOMERSINFO", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[19]={ id: 19, fld:"",grid:0};
   GXValidFnc[20]={ id: 20, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"UNNAMEDTABLEFSCUSTOMERSGRID",grid:21};
   GXValidFnc[23]={ id: 23, fld:"",grid:21};
   GXValidFnc[24]={ id: 24, fld:"",grid:21};
   GXValidFnc[25]={ id: 25, fld:"",grid:21};
   GXValidFnc[26]={ id:26 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:21,gxgrid:this.CustomersgridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTHOMELANDINGSAMPLELOGOS__LOGO",gxz:"ZV11GXV2",gxold:"OV11GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.GXV2=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV11GXV2=Value},v2c:function(row){gx.fn.setGridMultimediaValue("SDTHOMELANDINGSAMPLELOGOS__LOGO",row || gx.fn.currentGridRowImpl(21),gx.O.GXV2,"")},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV2=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTHOMELANDINGSAMPLELOGOS__LOGO",row || gx.fn.currentGridRowImpl(21))},nac:gx.falseFn};
   GXValidFnc[27]={ id: 27, fld:"",grid:0};
   GXValidFnc[28]={ id: 28, fld:"",grid:0};
   GXValidFnc[29]={ id: 29, fld:"TESTIMONIALSSECTION",grid:0};
   GXValidFnc[30]={ id: 30, fld:"",grid:0};
   GXValidFnc[31]={ id: 31, fld:"",grid:0};
   GXValidFnc[32]={ id: 32, fld:"TESTIMONIALSTITLE", format:0,grid:0, ctrltype: "textblock"};
   GXValidFnc[33]={ id: 33, fld:"",grid:0};
   GXValidFnc[34]={ id: 34, fld:"",grid:0};
   GXValidFnc[36]={ id: 36, fld:"UNNAMEDTABLEFSFSTESTIMONIALS",grid:35};
   GXValidFnc[37]={ id: 37, fld:"",grid:35};
   GXValidFnc[38]={ id: 38, fld:"",grid:35};
   GXValidFnc[39]={ id: 39, fld:"",grid:35};
   GXValidFnc[40]={ id:40 ,lvl:3,type:"svchar",len:400,dec:0,sign:false,ro:1,isacc:0, multiline:true,grid:35,gxgrid:this.FstestimonialsContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSDESCRIPTION",gxz:"ZV13GXV4",gxold:"OV13GXV4",gxvar:"GXV4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV4=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV13GXV4=Value},v2c:function(row){gx.fn.setGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSDESCRIPTION",row || gx.fn.currentGridRowImpl(35),gx.O.GXV4,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV4=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSDESCRIPTION",row || gx.fn.currentGridRowImpl(35))},nac:gx.falseFn};
   GXValidFnc[41]={ id: 41, fld:"",grid:35};
   GXValidFnc[42]={ id: 42, fld:"",grid:35};
   GXValidFnc[43]={ id: 43, fld:"UNNAMEDTABLE1",grid:35};
   GXValidFnc[44]={ id: 44, fld:"",grid:35};
   GXValidFnc[45]={ id: 45, fld:"",grid:35};
   GXValidFnc[46]={ id: 46, fld:"",grid:35};
   GXValidFnc[47]={ id:47 ,lvl:3,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:35,gxgrid:this.FstestimonialsContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSNAME",gxz:"ZV14GXV5",gxold:"OV14GXV5",gxvar:"GXV5",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV5=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV14GXV5=Value},v2c:function(row){gx.fn.setGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSNAME",row || gx.fn.currentGridRowImpl(35),gx.O.GXV5,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV5=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSNAME",row || gx.fn.currentGridRowImpl(35))},nac:gx.falseFn};
   GXValidFnc[48]={ id: 48, fld:"",grid:35};
   GXValidFnc[49]={ id: 49, fld:"",grid:35};
   GXValidFnc[50]={ id: 50, fld:"",grid:35};
   GXValidFnc[51]={ id:51 ,lvl:3,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:35,gxgrid:this.FstestimonialsContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSCOMPANY",gxz:"ZV15GXV6",gxold:"OV15GXV6",gxvar:"GXV6",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV6=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV15GXV6=Value},v2c:function(row){gx.fn.setGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSCOMPANY",row || gx.fn.currentGridRowImpl(35),gx.O.GXV6,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV6=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SDTHOMETESTIMONIALS__SDTHOMETESTIMONIALSCOMPANY",row || gx.fn.currentGridRowImpl(35))},nac:gx.falseFn};
   this.ZV11GXV2 = "" ;
   this.OV11GXV2 = "" ;
   this.ZV13GXV4 = "" ;
   this.OV13GXV4 = "" ;
   this.ZV14GXV5 = "" ;
   this.OV14GXV5 = "" ;
   this.ZV15GXV6 = "" ;
   this.OV15GXV6 = "" ;
   this.GXV2 = "" ;
   this.GXV4 = "" ;
   this.GXV5 = "" ;
   this.GXV6 = "" ;
   this.Events = {"e140s2_client": ["ENTER", true] ,"e150s2_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'CUSTOMERSGRID_nFirstRecordOnPage'},{av:'CUSTOMERSGRID_nEOF'},{av:'AV5SDTHomeLandingSampleLogos',fld:'vSDTHOMELANDINGSAMPLELOGOS',grid:21,pic:''},{av:'nRC_GXsfl_21',ctrl:'CUSTOMERSGRID',prop:'GridRC'},{av:'FSTESTIMONIALS_nFirstRecordOnPage'},{av:'FSTESTIMONIALS_nEOF'},{av:'AV6SDTHomeTestimonials',fld:'vSDTHOMETESTIMONIALS',grid:35,pic:''},{av:'nRC_GXsfl_35',ctrl:'FSTESTIMONIALS',prop:'GridRC'}],[]];
   this.EvtParms["START"] = [[{av:'AV6SDTHomeTestimonials',fld:'vSDTHOMETESTIMONIALS',grid:35,pic:''},{av:'FSTESTIMONIALS_nFirstRecordOnPage'},{av:'nRC_GXsfl_35',ctrl:'FSTESTIMONIALS',prop:'GridRC'},{av:'CUSTOMERSGRID_nFirstRecordOnPage'},{av:'CUSTOMERSGRID_nEOF'},{av:'AV5SDTHomeLandingSampleLogos',fld:'vSDTHOMELANDINGSAMPLELOGOS',grid:21,pic:''},{av:'nRC_GXsfl_21',ctrl:'CUSTOMERSGRID',prop:'GridRC'},{av:'FSTESTIMONIALS_nEOF'}],[{av:'AV5SDTHomeLandingSampleLogos',fld:'vSDTHOMELANDINGSAMPLELOGOS',grid:21,pic:''},{av:'CUSTOMERSGRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_21',ctrl:'CUSTOMERSGRID',prop:'GridRC'},{av:'AV6SDTHomeTestimonials',fld:'vSDTHOMETESTIMONIALS',grid:35,pic:''},{av:'FSTESTIMONIALS_nFirstRecordOnPage'},{av:'nRC_GXsfl_35',ctrl:'FSTESTIMONIALS',prop:'GridRC'}]];
   this.EvtParms["FSTESTIMONIALS.LOAD"] = [[],[]];
   this.EvtParms["CUSTOMERSGRID.LOAD"] = [[],[]];
   this.addBCProperty("Sdthomelandingsamplelogos", ["Logo"], this.GXValidFnc[21], "AV5SDTHomeLandingSampleLogos");
   this.addGridBCProperty("Sdthometestimonials", ["SDTHomeTestimonialsDescription"], this.GXValidFnc[40], "AV6SDTHomeTestimonials");
   this.addGridBCProperty("Sdthometestimonials", ["SDTHomeTestimonialsName"], this.GXValidFnc[47], "AV6SDTHomeTestimonials");
   this.addGridBCProperty("Sdthometestimonials", ["SDTHomeTestimonialsCompany"], this.GXValidFnc[51], "AV6SDTHomeTestimonials");
   this.Initialize( );
});
gx.wi( function() { gx.createParentObj(wwpbaseobjects.noticias);});
